name: AdventurePlugin
version: '1.0'
main: com.ryderbelserion.adventure.AdventurePlugin
bootstrapper: com.ryderbelserion.adventure.AdventureStrap
description: A burner plugin testing all things Adventure
api-version: '1.20.6'